In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [4]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
float(a[1])

1.0

In [7]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [8]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [9]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points.shape

torch.Size([3, 2])

In [13]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points[0, 1]

tensor(1.)

In [16]:
points[0]

tensor([4., 1.])

## Indexing tensors

In [17]:
some_list = list(range(6))

In [18]:
# all elements in the list
some_list[:]

[0, 1, 2, 3, 4, 5]

In [19]:
# from element 1 inclusive to element 4 exclusive
some_list[1:4]

[1, 2, 3]

In [20]:
# from element 1 inclusive to the end of the list
some_list[1:]

[1, 2, 3, 4, 5]

In [21]:
# from the start of the list to element 4 exclusive
some_list[:4]

[0, 1, 2, 3]

In [22]:
# from the start of the list to one before the last element
some_list[:-1]

[0, 1, 2, 3, 4]

In [23]:
# from element 1 inclusive to element 4 exclusive, in steps of 2
some_list[1:4:2]

[1, 3]

In [24]:
# all rows after the first; implicitly all columns
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [25]:
# all rows after the first; first column
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [26]:
# All rows after the first; first column
points[1:, 0]

tensor([5., 2.])

In [27]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])